# Используем официальный образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код приложения
COPY . .

# Собираем проект для продакшена
RUN npm run build

# Открываем порт для продакшен-сервера
EXPOSE 3000

# Команда для запуска продакшен-сервера
CMD ["npm", "start"]