# Берем вашу копию из GHCR
FROM ghcr.io/alexanderjkochnev/my-postgres:alpine

# Гарантируем наличие папки и прав, даже если при копировании в GHCR что-то потерялось
USER root
RUN mkdir -p /var/lib/postgresql/data && \
    chown -R postgres:postgres /var/lib/postgresql/data && \
    chmod 700 /var/lib/postgresql/data

# Возвращаемся к пользователю postgres
USER postgres