# Используем Node.js 20 (меньше 20 конфликтует с vite)
FROM node:20-alpine

WORKDIR /app

# Копируем зависимости
COPY package*.json ./

# Устанавливаем зависимости
# RUN npm ci
RUN npm install

# Копируем исходный код (в dev-режиме лучше монтировать через volume, но копируем на всякий случай)
COPY . .

# Открываем порт (Vite default port)
EXPOSE 5173

# Запускаем dev-сервер
# Важно: убедитесь, что dev-сервер слушает 0.0.0.0
CMD ["npm", "run", "dev"]