server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    # Отключаем sendfile, чтобы избежать проблем с обновлением файлов в Docker volumes
    sendfile off;

    location / {
        try_files $uri $uri/ /index.html; # Нужно для SPA (маршрутизация Preact)
        # Запрещаем кэшировать index.html
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # Кэширование статики
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        # expires 1y;
        # add_header Cache-Control "public, no-transform";
        # боьба с кэшем
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}